- className: dk.fust.docgen.datadict.DataDictionaryConfiguration
  documentationFile: documentation.yaml
  tableFormatter:
    className: dk.fust.docgen.csv.format.table.CSVTableFormatter
  destination:
    className: dk.fust.docgen.destination.FileDestination
    file: data-dictionary.csv
- className: dk.fust.docgen.datadict.DataDictionaryConfiguration
  documentationFile: documentation.yaml
  addDescriptionForFile: true
  tableFormatter:
    className: dk.fust.docgen.excel.format.table.ExcelBase64TableFormatter
    headerExcelStyle:
      fontName: Verdana
      fontHeightInPoints: 11
      fontColor: WHITE
      bold: true
      backgroundColor: 88, 88, 88
    secondaryHeaderExcelStyle:
      fontName: Verdana
      fontHeightInPoints: 9
      fontColor: WHITE
      bold: true
      backgroundColor: GREY_50_PERCENT
    evenRowExcelStyle:
      fontName: Verdana
      fontHeightInPoints: 9
      fontColor: BLACK
      bold: false
      backgroundColor: 220, 220, 220
    oddRowExcelStyle:
      fontName: Verdana
      fontHeightInPoints: 9
      fontColor: BLACK
      bold: false
      backgroundColor: 240, 240, 240
    defaultColumnWidth: 50
    columnWidths:
      - className: dk.fust.docgen.excel.format.table.model.ColumnWidth
        columnNumber: 0
        width: 20
      - className: dk.fust.docgen.excel.format.table.model.ColumnWidth
        columnNumber: 1
        width: 20
      - className: dk.fust.docgen.excel.format.table.model.ColumnWidth
        columnNumber: 2
        width: 12
      - className: dk.fust.docgen.excel.format.table.model.ColumnWidth
        columnNumber: 3
        width: 12
      - className: dk.fust.docgen.excel.format.table.model.ColumnWidth
        columnNumber: 4
        width: 14
      - className: dk.fust.docgen.excel.format.table.model.ColumnWidth
        columnNumber: 5
        width: 12
  destination:
    className: dk.fust.docgen.destination.Base64FileDestination
    file: data-dictionary.xlsx
- className: dk.fust.docgen.datadict.DataDictionaryMetaInfoConfiguration
  documentationFile: documentation.yaml
  tableFormatter:
    className: dk.fust.docgen.format.table.JsonTableFormatter
  destination:
    className: dk.fust.docgen.destination.FileDestination
    file: data-dictionary-meta-info.json
